# Generated by Django 4.2.10 on 2024-04-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Secret text')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Secret key')),
                ('secret_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Secret key for open Secret')),
                ('lifetime', models.CharField(choices=[('30_min', '30 minutes'), ('1_hour', '1 hour'), ('4_hour', '4 hours'), ('12_hour', '12 hours'), ('1_day', '1 day'), ('7_day', '7 days')], default='1_hour', max_length=10, verbose_name='Lifetime of Secret')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('is_open', models.BooleanField(default=False, verbose_name='is Open')),
            ],
            options={
                'verbose_name': 'Secret',
                'verbose_name_plural': 'Secrets',
            },
        ),
    ]
